config/routes.rb
PovrayShortcode::Application.routes.draw do
  resources :users do
    member do
      get :voting_for
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]

  resources :entries do
    member do
      get :voters
    end
  end
  
  resources :votes, :only => [:create, :destroy]
  
  resources :entries, :only => [:shortcode]
  
  resources :contests do
    member do
      get :gallery
      get :results
    end
  end
  
  

  match '/signup', :to => 'users#new' #controller is users, method is new
  match '/signin', :to => 'sessions#new' #controller is sessions, method is new
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact' #controller is pages, method is contact
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  match '/newentry', :to => 'entries#new'
  
  match '/newcontest', :to => 'contests#new'
  
  match '/results', :to => 'entries#results'
  
  match '/entries/:id/renderstatus', :to => 'entries#renderstatus'
  match '/contests/:id/gallery', :to => 'contests#gallery'

  root :to => 'pages#home'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

end

app/models/entry.rb
require 'digest'
require 'net/http'
require 'uri'

class Entry < ActiveRecord::Base
  attr_accessible :title, :shortcode, :longcode, :comments, :picture
  
  belongs_to :user
  has_many :votes
  belongs_to :contest
  
  has_many :reverse_relationships, :foreign_key => "entry_id",
                                   :class_name => "Vote"
  has_many :voters, :through => :reverse_relationships, :source => :user
  
  validates :title, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true
  validates :shortcode, :presence => true, :length => { :maximum => 256 }
  validates :longcode, :length => { :maximum => 8192 }
  validates :comments, :length => { :maximum => 8192 }
  
  class UniquetitleValidator < ActiveModel::EachValidator
    def validate_each(entry, attribute, value)
      if Entry.all.find_all{|e| e.contest == Contest.current_contest and
                                e.user_id == entry.user_id and
                                e.title == value and
                                e.id != entry.id }.size > 0
        entry.errors[attribute] << "must be unique to your other entries."
        return false
      end
      return true
    end
  end
  
  validates :title, :uniquetitle => true
  
  default_scope :order => 'entries.created_at DESC'
  
  
  def self.pov_server
    "http://pscc.2-complex.com/"
  end
  
  def image_name
    'im' + hash_entry_params + hash_shortcode
  end
  
  def image_url
  	Entry.pov_server + "images/" + image_name + '.png'
  end
  
  def thumbnail_url
  	Entry.pov_server + "thumbnails/" + image_name + '.png'
  end
  
  def shortcode_url
  	Entry.pov_server + "shortcode/" + image_name + '.pov'
  end
  
  def render_request
    res = Net::HTTP.post_form(URI.parse(Entry.pov_server + 'cgi-bin/request.py'),
        {'name'=>image_name,
         'code'=>shortcode,
         'ini'=>contest.ini,
         'thumbnailini'=>contest.thumbnailini,
         'key'=>key})
  end
  
  def render_status
    res = Net::HTTP.post_form(URI.parse(Entry.pov_server + 'cgi-bin/status.py'),
        {'name'=>image_name,
         'key'=>key})
    res.body
  end
  
  def render_status_html
    res = Net::HTTP.post_form(URI.parse(Entry.pov_server + 'cgi-bin/view.py'),
        {'name'=>image_name,
         'key'=>key})
    # a hack to turn relative path names for images into absolute paths
    res.body.gsub( /<\s*img\s+src\s*=\s*"/, '<img src = "' + Entry.pov_server + 'cgi-bin/')
  end
  
  def key
    Digest::SHA2.hexdigest(image_name + String('#bananas23'))
  end
  
  def shortcode_full_hash
    Digest::SHA2.hexdigest(shortcode)
  end
  
  def score
  	r = 0
  	votes.each do |v|
  		r += v.weight
  	end
  	return r
  end
  
  def acquire_contest
    # sets the contest_id field of the entry if it doesn't have it already.
    # this is only because we had entries in our test database before we added contests.
    # we shouldn't need this anymore.
    now = Contest.current_time
	if not contest
	  Contest.all.each do |c|
        if now >= c.startdate and created_at >= c.startdate and created_at < c.entrydeadline
		  contest = c
		  save
		  return c
        end
	  end
	end
  end
  
  def editable?
    now = Contest.current_time
    if contest and now <= contest.entrydeadline
      return true
    end
    return false
  end
  
  def publicly_visible?
    acquire_contest
    now = Contest.current_time
    if contest and now >= contest.votingend
      return true
    end
    return false
  end
  
  def allows_vote_from?(user)
    Contest.current_contest and Contest.current_contest.voting_window? and user and user.may_vote?
  end
  
  private
    def hash_shortcode
      Digest::SHA2.hexdigest(shortcode + String(user_id))[0..5]
    end
    
    def hash_entry_params
      Digest::SHA2.hexdigest(String(user_id) + String(id))[0..5]
    end
end


# == Schema Information
#
# Table name: entries
#
#  id                   :integer         not null, primary key
#  title                :string(255)
#  user_id              :integer
#  shortcode            :text
#  longcode             :text
#  comments             :text
#  created_at           :datetime
#  updated_at           :datetime
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate, :except => [:results]
  before_filter :check_editable, :only => [:edit, :update, :destroy]
  # before_filter :admin_user, :only => :voters

  def show
    @entry = Entry.find(params[:id])
    @title = @entry.title
  end
  
  def index
    @title = "All entries"
    @entries = Entry.paginate(:page => params[:page])
  end
  
  def results
    @title = "Results"
    @entries = Entry.paginate(:page => params[:page])
  end

  def new # page that allows for creation of a new entry!!!
    @entry = Entry.new if signed_in?
    @title = "New entry"
  end

  def create
    @entry = current_user.entries.build(params[:entry])
    @entry.contest = Contest.current_contest
    if @entry.save
      flash[:success] = "Entry created. A new render request has been submitted."
      @entry.render_request
      redirect_to current_user
    else
      render 'entries/new'
    end
  end
  
  def update
    @entry = Entry.find(params[:id])
    old_shortcode = @entry.shortcode
    if @entry.update_attributes(params[:entry])
      message = "Entry updated."
      
      if old_shortcode and old_shortcode != @entry.shortcode
        @entry.render_request
    	message += " A new render request has been submitted."
      end

      flash[:success] = message
    
      redirect_to current_user
    else
      render 'entries/edit'
    end
  end
  
  def edit
    @entry = Entry.find(params[:id])
    @title = "Edit Entry"
  end
  
  def renderstatus
    @entry = Entry.find(params[:id])
    @title = "Entry Render Status"
  end

  def destroy
    Entry.find(params[:id]).destroy
    flash[:success] = "Entry deleted."
    redirect_to current_user
  end
  
  def voters
    @title = "Users voting for this entry"
    @entry = Entry.find(params[:id])
    @users = @entry.voters
  end
  
  private
  
  def check_editable
    @entry = Entry.find(params[:id])
    if current_user.admin? or @entry.editable?
      return true
    else
      flash[:error] = "Entry not editable."
      redirect_to current_user
    end
    return false
  end
end

app/helpers/entries_helper.rb
require 'digest'

module EntriesHelper
	# takes the list of entries, and returns a structure with two lists,
	# :winners and :runnersup
	def winners(l)
		s = ''
		# break ties with the length of the shrotcode,
		# break ties after that with the code itself but hashed for an extra element
		# of pseudo-randomness.
		nl = l.sort_by {|e| [-e.score, e.shortcode.size, e.shortcode_full_hash]}
		# put the runners up in alphabetical order.
		
		if nl.size < 3
		  return {:winners => nl, :runnersup => []}
		end
		return {:winners => nl[0..2], :runnersup => nl[3..nl.size].sort_by {|e| e.title.downcase}}
	end
	
	# searches for substrings of s with no space or tab of length at least l
	# and artificially inserts newlines to break them up.
	def wrap(s)
	  r = ""
	  i = 0
	  n = s.length
	  sofar = 0
	  while i < n
		r << String(s[i])
		
		if /\s/ =~ s[i]
		  sofar = 0
		else
		  sofar += 1
		end
		
		if sofar >= 100
		  r << "\n"
		  sofar = 0
		end
		i+=1
	  end
	  return r
	end
end

app/views/entries/_cast_vote.html.erb
<%= form_for current_user.votes.build(:entry_id => @entry.id),
		:remote => true do |f| %>
  <%= f.hidden_field :entry_id %>
  <div class="actions">
    <%= f.submit "Vote" %>
    <%= select_tag(:weight, options_for_select([['3 points', 3], ['2 points', 2], ['1 point', 1]], 3)) %>
  </div>
<% end %>

app/views/entries/_cast_vote_form.html.erb
  <div id="vote_form">
    <% if current_user.votedfor?(@entry) %>
      <%= render 'unvote' %>
    <% else %>
      <%= render 'cast_vote' %>
    <% end %>
  </div>

app/views/entries/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
  <%= f.label :"title" %><br />
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :"shortcode" %><br/>
  <p style = "font-size : .75em; margin-bottom : 0;">
  Gets rendered and judged in the contest.  May not exceed 256 characters.<br/>
  </p>
  
  <%= f.text_area :shortcode,
    :id => "shortcode_textarea",
  	:onKeyUp => "updateTextCounters();" %><br/>

  <span id = "shortcode_count" value=""></span> characters left
</div>

<div class="field">
  <%= f.label :"longcode" %><br/>
  <p style = "font-size : .75em; margin-bottom : 0;">
  (Optional)  A longer, more human-readable version of the code.
  </p>
  <%= f.text_area :longcode %>
</div>
<div class="field">
  <%= f.label :"comments" %><br/>
  <p style = "font-size : .75em; margin-bottom : 0;">
  (Optional) Anything else you would like to add.
  </p>
  <%= f.text_area :comments %>
</div>

<script language="JavaScript">

function textCounter(field, countfield, enforce, limit)
{
	if (enforce && field.value.length > limit)
		field.value = field.value.substring(0, limit);
	
	countfield.innerHTML = limit - field.value.length;
}

function udpateTextCounters()
{
	textCounter(
		document.getElementById("shortcode_textarea"),
		document.getElementById("shortcode_count"), false, 256);
}

setInterval(udpateTextCounters, 100);

</script>

app/views/entries/_thumbgrid.html.erb
<table class="thumbnail">
  <% cols = 3 %>
  <% i = 0 %>
  
  <% entries.each do |entry| %>
  	<% puts entry %>
    <% url = entry_path(entry) %>
    
    <% if i%cols==0 %> <tr> <% end %>
      <td>
      
      <% if signed_in? %>
        <% vote = current_user.votes.find_by_entry_id(entry.id) %>
      <% end %>
      
      <% if vote && signed_in? %>
        <div style="padding:1px; outline-style: solid;">
      <% else %>
        <div>
      <% end %>
      
      <center>
      
      <% if vote && signed_in? %>
        <%= pluralize(vote.weight, 'point') %><br/>
      <% else %>
        <br/>
      <% end %>
     	
      <a href = <%= url %> >
      <img src = "<%= entry.thumbnail_url %>"
           onerror="this.src='images/default_thumb.png';">
      <br/>
      <h3 style="font-size: 1.1em;"><%= entry.title %></h3>
      </a>
      </center>
      </div>
      </td>
    <% if i%cols==cols-1 %> </tr> <% end %>
    <% i+=1 %>
  <% end %>
</table>

app/views/entries/_thumbnail.html.erb
<tr>
  <td class="">
    <h2><span class="title"><%= entry.title %></span></h2>
    
    <nav>
    <%= link_to "edit", edit_entry_path(entry) %>
    </nav>
    
    <br/>
    
    <label>Short Code</label>
    <pre class="shortcode"><%= entry.shortcode %></pre>
    
    <% if entry.longcode? %>
      <label>Long Code</label>
      <pre class="longcode"><%= entry.longcode %></pre>
    <% end %>
    
    <% if entry.comments? %>
	  <label>Comments</label>
	  <pre class="comments"><%= entry.comments %></pre>
    <% end %>

    <span class="timestamp">
      Posted <%= time_ago_in_words(entry.created_at) %> ago.
    </span>
    
  </td>
</tr>

app/views/entries/_unvote.html.erb
<%= form_for current_user.votes.find_by_entry_id(@entry),
             :html => { :method => :delete },
             :remote => true do |f| %>
  <div class="actions">
    <%= f.submit "Remove vote" %>
  </div>
<% end %>

app/views/entries/_vote.html.erb
<%= form_for current_user.votes.build(:entry_id => @entry.id),
		:remote => true do |f| %>
  <div><%= f.hidden_field :entry_id %></div>
  <div class="actions"><%= f.submit "Vote" %></div>
<% end %>

app/views/entries/_vote_info.html.erb
<div id = "vote_info">

<% contest = Contest.current_contest %>
<% if contest and contest.voting_window? and current_user and current_user.may_vote? %>

<h1>Votes</h1>

<nav class="round">
  <ul>
    <li>  <%= link_to "Voting Gallery", '/contests/' + Contest.current_contest.id.to_s + '/gallery' %></li>
  </ul>
</nav>

Your choices for <%= contest.title %>

<div class = "round box">

<% vc = current_user.votes_for_contest(contest) %>

<% if vc.size > 0 %>

<!--Work-around for a bug where a phantom vote object
    with no id or weight appears in the list--!>
<% revised_vote_list = [] %>
<% current_user.votes_for_contest(contest).each do |vote| %>
<%   if vote.id %>
<%     revised_vote_list << vote %>
<%   end %>
<% end %>

<table>

<tr>
<td>Points</td>
<td>Title</td>
</tr>

<% revised_vote_list.sort_by! {|vote| -vote.weight} %>
<% revised_vote_list.each do |vote| %>
<%if vote.id %>
<tr>
<td><%= h vote.weight%></td>
<td><%= h Entry.find_by_id(vote.entry_id).title %> </td>
</tr>
<% end %>
<% end %>
</table>

<% vote = current_user.votes.find_by_entry_id(@entry) %>
<% if vote %>
<hr/>
<%= "You have voted for this entry for " + pluralize(vote.weight, 'point') + '.' %>
<% end %>
<% end %>

</div>

</div>

<% end %>

app/views/entries/edit.html.erb
<h1>Edit Entry</h1>

<%= form_for(@entry) do |f| %>

  <%= render 'fields', :f => f %>
  
  <nav>
    <%= link_to "delete", @entry,
    	:method => :delete,
    	:confirm => "Deleting Entry.  Are you sure?",
        :title => "Delete #{@entry.title}" %>
  </nav>
  
  <div class="actions">
    <%= f.submit "Update Entry" %>
  </div>
<% end %>

app/views/entries/index.html.erb
<h1 style="margin-top: 10px;" >Voting Gallery</h1>

<%= will_paginate %>

<% contest = Contest.current_contest %>

<% if current_user and current_user.may_vote? %>

<% if contest and contest.voting_window? %>

<% render :partial => "gallery", :locals => {:entries => 
	@entries.find_all{|e| e.contest == contest}.sort_by{|e| e.image_name} } %>

<% else %>

Voting gallery not available.

<% end %>

<% else %>

Must have an entry in the current contest to vote.

<% end %>

<%= will_paginate %>

<% if signed_in? %>
  <%= render 'vote_info' %>
<% end %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= form_for(@entry) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Submit Entry" %>
  </div>
<% end %>

app/views/entries/renderstatus.html.erb
<h1>Entry Render Status</h1>

<%= raw @entry.render_status_html %>

app/views/entries/show.html.erb
<% if @entry.contest == Contest.current_contest %>
  <% if @entry.allows_vote_from?(current_user) %>
    <%= render 'vote_info' %>
    <% if signed_in? %>
      <% if current_user.id == @entry.user_id %>
        This entry is yours.
      <% else %>
        <%=  render "cast_vote_form" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<table class="entries">
  <%= render @entry %>
</table>

app/views/entries/voters.html.erb
Voting for this entry:

<ul class="users">
  <%= render @users %>
</ul>