config/routes.rb
PovrayShortcode::Application.routes.draw do
  resources :users do
    member do
      get :voting_for
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]

  resources :entries do
    member do
      get :voters
    end
  end
  
  resources :votes, :only => [:create, :destroy]
  
  resources :entries, :only => [:shortcode]
  
  resources :contests do
    member do
      get :gallery
      get :results
    end
  end
  
  

  match '/signup', :to => 'users#new' #controller is users, method is new
  match '/signin', :to => 'sessions#new' #controller is sessions, method is new
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact' #controller is pages, method is contact
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  match '/newentry', :to => 'entries#new'
  
  match '/newcontest', :to => 'contests#new'
  
  match '/results', :to => 'entries#results'
  
  match '/entries/:id/renderstatus', :to => 'entries#renderstatus'
  match '/contests/:id/gallery', :to => 'contests#gallery'

  root :to => 'pages#home'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  attr_accessible :title, :rules, :ini, :thumbnailini, :charlimit
  attr_accessible :startdate, :entrydeadline, :votingstart, :votingend
  
  has_many :entries
  has_many :votes
  
  validates :title, :presence => true, :length => { :maximum => 200 }
  
  @@time_warp = 0
  
  def self.time_warp
    @@time_warp
  end
  
  def self.time_warp=(n)
    @@time_warp = n
  end
  
  def self.current_time
    Time.now.utc + @@time_warp
  end
  
  def self.current_contest
    now = current_time
    
    # look through all contests
    all.each do |contest|
      if now >= contest.startdate &&
         now <= contest.votingend
        return contest
      end
    end
    return nil # no contest
  end
  
  def self.latest_contest
    now = current_time
    return all.max_by {|c| [now > current_time ? 1 : 0, c.startdate]}
  end
  
  def self.next_contest
    now = current_time
    
    n = all.max_by {|c| c.startdate}
    if n and n.startdate > now
    	return n
    end
    
    return nil
  end
  
  def submission_window?
    now = Contest.current_time
    return (now >= startdate and now < entrydeadline)
  end
  
  def rendering?
    now = Contest.current_time
    return (now >= entrydeadline and now < votingstart)
  end
  
  def voting_window?
    now = Contest.current_time
    return (now >= votingstart and now < votingend)
  end
  
  def over?
    now = Contest.current_time
    return (now > votingend)
  end
  
end

Contest.time_warp = 0 * 24 * 60 * 60


# == Schema Information
#
# Table name: contests
#
#  id            :integer         not null, primary key
#  title         :string(255)
#  charlimit     :integer
#  startdate     :datetime
#  entrydeadline :datetime
#  votingstart   :datetime
#  votingend     :datetime
#  rules         :text
#  ini           :text
#  thumbnailini  :text
#  created_at    :datetime
#  updated_at    :datetime
#

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_filter :authenticate, :except => :show
  before_filter :admin_user, :except => :show
  
  def show
    @contest = Contest.find(params[:id])
    @title = @contest.title
  end
  
  def index
    @title = "Contests"
    @contests = Contest.paginate(:page => params[:page])
  end
  
  def new # page that allows for creation of a new contest!!!
    @contest = Contest.new if signed_in?
    @title = "New Contest"
  end
  
  def create
    @contest = Contest.new(params[:contest])
    if @contest.save
      flash[:success] = "Contest created."
      redirect_to @contest
    else
      render 'contests/new'
    end
  end
  
  def edit
    @contest = Contest.find(params[:id])
    @title = "Edit Contest"
  end
  
  def update
    @contest = Contest.find(params[:id])
    if @contest.update_attributes(params[:contest])
      flash[:success] = "Contest updated."
      redirect_to @contest
    else
      render 'contests/edit'
    end
  end
  
  def destroy
    Contest.find(params[:id]).destroy
    flash[:success] = "Contest deleted."
    redirect_to contests_path
  end
  
  def admin_user
    current_user.admin?
  end
  
  def gallery
    @contest = Contest.find(params[:id])
    @entries = @contest.entries.paginate(:page => params[:page])
  end
  
  def results
    @contest = Contest.find(params[:id])
    @all_entries = @contest.entries.paginate(:page => params[:page])
    @all_contests = Contest.all.sort_by {|c| -c.startdate.to_i}
  end
end

app/views/contests/_contest.html.erb
<h2> <%= contest.title %> </h2>

<% if current_user and current_user.admin? %>
<nav>
  <ul>
    <li><%= link_to "edit", edit_contest_path(contest) %></li>
    <li><%= link_to "show", contest_path(contest) %></li>
  </ul>
</nav>
<% end %>

<div class="rules">

<h2>Rules</h2>

<p>
To submit an entry, just sign up, log in, navigate to "My Home" and
click the "New Entry" button.  On the entry deadline, any entry with valid povray
code that renders an image will enter the voting gallery.  All users with at
least one entry will be able to vote for the winner.
</p>

<p><%=h contest.rules %></p>

<hr/>

<h2>Important Dates</h2>

<p>
<b><%=h contest.entrydeadline.getlocal.strftime("%A %B %d, %Y at %I:%M %p %Z") %></b>.  Entries are due.
All entries submitted for this contest will be saved and become part of the voting gallery.
Contestants may no longer edit or delete their entries.  Entries are given some time
to render before voting begins.
</p>

<p>
<b><%=h contest.votingstart.getlocal.strftime("%A %B %d, %Y at %I:%M %p %Z") %></b> Voting begins.
Contestents vote for their top three choices.  Contestents may not vote for their own entries.
</p>

<p>
<b><%=h contest.votingend.getlocal.strftime("%A %B %d, %Y at %I:%M %p %Z") %></b>
Voting closes, contest results are posted.<br/>
</p>

<hr/>

<h2>Ini Files</h2>

<p>
Entries will be rendered once to create a thumbnail, and once to create a
full sized using the following ini files.
</p>

<label>Ini</label>
  <div class="code"><%=h contest.ini %></div>
<br/>

<label>Ini for Thumbnail</label>
  <div class="code"><%=h contest.thumbnailini %></div>
<br/>

</div>

<% if current_user and current_user.admin? %>
<label>Start Date<label>
  <div class="date"><%=h contest.startdate %></div>
<br/>

<label>Entry Deadline<label>
  <div class="date"><%=h contest.entrydeadline %></div>
<br/>

<label>Voting Start<label>
  <div class="date"><%=h contest.votingstart %></div>
<br/>

<label>Voting End<label>
  <div class="date"><%=h contest.votingend %></div>
<br/>
<% end %>

app/views/contests/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
  <%= f.label :"title" %><br />
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :"rules" %><br />
  <%= f.text_area :rules %><br/>
</div>

<div class="field">
  <%= f.label :"ini" %><br />
  <%= f.text_area :ini %><br/>
</div>

<div class="field">
  <%= f.label :"thumbnail ini" %><br />
  <%= f.text_area :thumbnailini %><br/>
</div>


<div class="field">
  <%= f.label :"start date" %><br />
  <%= f.text_field :startdate %>
</div>

<div class="field">
  <%= f.label :"entry deadline" %><br />
  <%= f.text_field :entrydeadline %>
</div>

<div class="field">
  <%= f.label :"voting start" %><br />
  <%= f.text_field :votingstart %>
</div>

<div class="field">
  <%= f.label :"voting end" %><br />
  <%= f.text_field :votingend %>
</div>

app/views/contests/_mini_contest.html.erb
<li>
  <%= link_to mini_contest.title, '/contests/' + mini_contest.id.to_s + '/results' %>
</li>

app/views/contests/edit.html.erb
<h1>Edit Contest</h1>

<%= form_for(@contest) do |f| %>

  <%= render 'fields', :f => f %>
  
  <nav>
    <%= link_to "delete", @contest,
    	:method => :delete,
    	:confirm => "Deleting Contest.  Are you sure... I mean really sure?",
        :title => "Delete #{@contest.title}" %>
  </nav>
  
  <div class="actions">
    <%= f.submit "Update Contest" %>
  </div>
<% end %>

app/views/contests/gallery.html.erb
<h1 style="margin-top: 10px;" >Entries in <%= @contest.title %></h1>

<%= will_paginate @entries %>

<% contest = Contest.current_contest %>

<% if current_user and current_user.may_vote? %>

<% if contest and contest.voting_window? %>

<%= render :partial => 'entries/thumbgrid', :locals => {:entries =>
	@entries.find_all{|e| e.contest == contest}.sort_by{|e| e.image_name} } %>

<% else %>

Voting gallery not available.

<% end %>

<% else %>

Must have an entry in the current contest to vote.

<% end %>

<%= will_paginate @entries %>

<% if signed_in? %>
  <%= render 'entries/vote_info' %>
<% end %>

app/views/contests/index.html.erb
<% if current_user.admin? %>

<h1 style="margin-top: 10px;" >Contests</h1>

<nav>
  <ul>
	<li><%= link_to "New Contest", newcontest_path %></li>
  </ul>
</nav>

<%= will_paginate %>

<%= render @contests.sort_by {|c| -c.startdate.to_i} %>

<%= will_paginate %>

<% end %>

app/views/contests/new.html.erb
<h1>New Contest</h1>

<%= form_for(@contest) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/contests/results.html.erb
<h1>Contest Winners</h1>

<% if @contest and @contest.over? %>

<% p = winners(@contest.entries) %>

<table class="thumbnail">
<% p[:winners].each do |entry| %>
<tr><td>
<center>
<% url = '../../entries/' + entry.id.to_s %>
<a href = <%= url %> >
<img width = 500 src = "<%= Entry.pov_server + 'images/' + entry.image_name %>"
    	onerror="this.src='../../images/default_thumb.png';">
<h3 style="font-size: 1.1em;"><%= entry.title %></h3>
</a>
</center>
</td></tr>

<% end %>
</table>

<% if p[:runnersup].size > 0 %>
  <h1>The Rest </h1>
  (in pseudorandom order)
<%= will_paginate @all_entries %>
  <table class="thumbnail">
    <% cols = 3 %>
    <% i = 0 %>
    <% p[:runnersup].each do |entry| %>
    <% url = '../../entries/' + entry.id.to_s %>
  
    <% if i%cols==0 %> <tr> <% end %>
      <td style="background-color: f00;">
      <center>
    
      <% vote = nil %>
      <% if current_user %>
      <% vote = current_user.votes.find_by_entry_id(entry.id) %>
      <% end %>
      
      <br/>
      <a href = <%= url %> >
      <img src = "<%= Entry.pov_server + 'thumbnails/' + entry.image_name %>"
         onerror="this.src='../../images/default_thumb.png';">
      <br/>
      <h3 style="font-size: 1.1em;"><%= entry.title %></h3>
      </a>
      </center>
      </td>
    <% if i%cols==cols-1 %> </tr> <% end %>
    <% i+=1 %>
    <% end %>
  </table>
<% end %>

<%= will_paginate @all_entries %>

<% else %>

<% if @contest %>
<%= @contest.title %> is in progress.  Results will be available on <%= @contest.votingend.strftime("%A %B %d, %Y at %I:%M %p %Z") %>.
<% end %>

<% end %>

<h2>Results from other Contests</h2>
<ul class="contests">
  <%= render :partial => 'mini_contest', :collection => @all_contests.find_all {|c| c.over?} %>
</ul>

app/views/contests/show.html.erb
<% if (current_user and current_user.admin?) or Contest.current_contest==@contest %>
<%= render @contest %>
<% else %>
Adminstrator access only.
<% end %>