config/routes.rb
PovrayShortcode::Application.routes.draw do
  resources :users do
    member do
      get :voting_for
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]

  resources :entries do
    member do
      get :voters
    end
  end
  
  resources :votes, :only => [:create, :destroy]
  
  resources :entries, :only => [:shortcode]
  
  resources :contests do
    member do
      get :gallery
      get :results
    end
  end
  
  

  match '/signup', :to => 'users#new' #controller is users, method is new
  match '/signin', :to => 'sessions#new' #controller is sessions, method is new
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact' #controller is pages, method is contact
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  match '/newentry', :to => 'entries#new'
  
  match '/newcontest', :to => 'contests#new'
  
  match '/results', :to => 'entries#results'
  
  match '/entries/:id/renderstatus', :to => 'entries#renderstatus'
  match '/contests/:id/gallery', :to => 'contests#gallery'

  root :to => 'pages#home'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password # need this, forget why though 

  #can be modified by outside users (such as users submitting requests with web browsers). 
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :entries, :dependent => :destroy
  has_many :votes
  has_many :voting_for, :through => :votes, :source => :entry
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true, :length => { :maximum => 100 }
  validates :email, :presence => true, 
            :format => { :with => email_regex }, 
            :uniqueness => { :case_sensitive => false } #Rails infers that :uniqueness should be true

  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password #callback

  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    # Compare encrypted_password with the encrypted version of
    # submitted_password.
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
    # handles the third case (password mismatch) implicitly, since in that case we reach the end of the method, which automatically returns nil. 
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  def votes_for_contest(contest)
    return votes.find_all{|vote| vote.contest == contest }
  end
  
  def votedfor?(entry)
    votes.find_by_entry_id(entry)
  end
  
  def cast_vote!(contest, entry, weight)
    vc = votes_for_contest(contest)
    vc.find_all{|vote| vote.weight == weight}.each do |vote|
      Vote.destroy(vote)
    end
    vote = votes.create!(:contest_id => contest.id, :entry_id => entry.id, :weight => weight)
    vote.contest = contest
    vote.save
	vote
  end
  
  def unvote!(entry)
    votes.find_by_entry_id(entry).destroy
  end
  
  def may_vote?
    return entries_in_contest(Contest.current_contest).size > 0
  end
  
  def entries_in_contest(contest)
    return entries.find_all{|e| e.contest == Contest.current_contest}
  end
  
  def entries_not_in_contest(contest)
    return entries.find_all{|e| e.contest != Contest.current_contest}
  end
  
  private

    def encrypt_password
      self.salt = make_salt if new_record?  #the self makes it refer to the attribute "salt" of the User object that we're currently looking at; if we ommitted "self" then it would make a new local variable called "salt" which is NOT WHAT WE WANT!!!
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string + "hrh")
    end
end


# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:show, :new, :create]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy
  before_filter :logged_in_user, :only => [:new, :create]

  def show # page that shows info about the user
    @user = User.find(params[:id])
    @entries = @user.entries.paginate(:page => params[:page])
    @title = @user.name  # in rails3, all embedded ruby text is escaped
                         # so "<" becomes "&lt;"
  end

  def new # page that allows for creation of a new user!!!
    @user = User.new
    @title = "Sign up"
  end

  def create #method for saving new user to db
    @user = User.new(params[:user])
    if @user.save
      #handle a successful save.
      sign_in @user
      flash[:success] = "Welcome to the POVRay shortcode contest!"
      redirect_to @user
    else
      @title = "Sign up"
      @user.password = ""
      @user.password_confirmation = ""
      render 'new'
    end
  end

  def edit
#   @user = User.find(params[:id]) -- removed when i added the correct_user function
    @title = "Edit user" 
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def index
    @title = "All Users"
    @users = User.paginate(:page => params[:page]) # :page generated by will_paginate
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  def voting_for
    #list all the entries that this user has voted for
    @user = User.find(params[:id])
    @title = @user.name + "'s votes"
    @entries = @user.voting_for.entries
  end

  private
  
    def correct_user
      @user = User.find(params[:id])  #this gets :id from the current url, right?
      redirect_to(root_path) unless current_user?(@user) #current_user? is in app/helpers/sessions_helper
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    #exercise 10.6.3 
    def logged_in_user
      redirect_to(root_path) unless !signed_in?
    end 
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar', 
                                            :gravatar => options)
  end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
    | <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
         :title => "Delete #{user.name}" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %> 
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  Use <a href="http://gravatar.com/emails" target="_blank">Gravatar</a> to add / change your icon.
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
  <p>Already have an account? <%= link_to "Sign in here!", signin_path %></p>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h2>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h2>
      
      <% if @user.id == current_user.id %>
      	<%= render 'entries/vote_info'%>
      	
        <% if Contest.current_contest and Contest.current_contest.submission_window? %>
          <h1 style="margin-top:10px;">Entries in <%= Contest.current_contest.title %></h1>
          <% if @user.entries_in_contest(Contest.current_contest).size == 0 %>
          (none so far)
          <% end %>
            
    	  <nav><ul><li><%= link_to "New Entry", newentry_path %></li></ul></nav>
        <% end %>
        
        <%= render @user.entries_in_contest(Contest.current_contest) %>
      <% end %>
      
      <% other_entries = @user.entries_not_in_contest(Contest.current_contest) %>
      
      <% if other_entries.size > 0 %>
      <h1 style="margin-top:10px;">Entries in Previous Contests</h1>
      
      <%= render :partial => "entries/thumbgrid", :locals => {:entries => 
	     other_entries.sort_by{|e| -e.created_at.to_i} } %>
      <% end %>
      
    </td>
  </tr>
</table>

app/views/users/votes.html.erb
<table class="entries">
  <%= render @entries %>
</table>

app/views/users/voting_for.html.erb
<table class="entries">
  <%= render @entries %>
</table>