config/routes.rb
PovrayShortcode::Application.routes.draw do
  resources :users do
    member do
      get :voting_for
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]

  resources :entries do
    member do
      get :voters
    end
  end
  
  resources :votes, :only => [:create, :destroy]
  
  resources :entries, :only => [:shortcode]
  
  resources :contests do
    member do
      get :gallery
      get :results
    end
  end
  
  

  match '/signup', :to => 'users#new' #controller is users, method is new
  match '/signin', :to => 'sessions#new' #controller is sessions, method is new
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact' #controller is pages, method is contact
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  match '/newentry', :to => 'entries#new'
  
  match '/newcontest', :to => 'contests#new'
  
  match '/results', :to => 'entries#results'
  
  match '/entries/:id/renderstatus', :to => 'entries#renderstatus'
  match '/contests/:id/gallery', :to => 'contests#gallery'

  root :to => 'pages#home'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://github.com/judytuna/shortcode-site-309">Github</a></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

  <div>
  	<div style="height:80px; margin-bottom: 15px;">
  	
    <div style="display: inline-block; vertical-align: top; height:100%">
     <%= link_to logo, root_path %>
    </div>
    
    <div style = "display: inline-block; float: bottom;">
    <h1 style="color: #ddd; padding: 5px; font-size: 2em;">
      Povray Short Code
    </h1>
    </div>
    
    <div class="round box" style="height:80%; padding: 10px;
      display: inline-block; float: right;">
      
      <div style="font-size: 1.3em;">
        <% if signed_in? %>
          <%= gravatar_for current_user, :size => 30 %>
	    <div style="display: inline-block; vertical-align: top;">
	      <%= current_user.name %>
	    </div>
        <% end %>
      </div>
      
      <nav class="round">
		<ul>
		  <% if signed_in? %>
		  <li><%= link_to "My Home", current_user %></li>
		  <% else %>
		  <li><%= link_to "Home", root_path %></li>
		  <% end %>

		  <% if signed_in? and Contest.current_contest and Contest.current_contest.voting_window? %>
		  <li><%= link_to "Voting Gallery", '/contests/' + Contest.current_contest.id.to_s + '/gallery' %></li>
		  <% end %>
		  
		  <% if signed_in? %>
		  <li><%= link_to "Results", '/contests/' + Contest.latest_contest.id.to_s + '/results' %></li>
		  <% end %>
		  
		  <% if signed_in? %>
		  <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
		  <% end %>
          
		  <% if signed_in? and current_user.admin? %>
		  <li><%= link_to "Contests", contests_path %></li>
		  <% end %>
		  
		  <% if signed_in? %>
		  <li><%= link_to "All Users", users_path %></li>
		  <% end %>
		  
		  <% if signed_in? %>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		  <% else %>
			<li><%= link_to "Sign in", signin_path %></li>
		  <% end %>
		</ul>
      </nav>
      
    </div>
	</div>
    
	<% contest = Contest.current_contest %>
    <% now = Contest.current_time %>
    
    <div class="round box" style="font-size:1.3em; padding: 10px; margin-top: 5px;">
    
    <% if contest %>
      <%= contest.title %> <%= link_to "(contest rules)", contest_path(contest) %>
      
      <% if now >= contest.startdate and now < contest.entrydeadline %>
        Entries due <%=h contest.entrydeadline.getlocal.strftime("%A %B %d, %Y at %I:%M %p (%Z)") %>.<br/>
        <%= time_between(contest.entrydeadline, Contest.current_time) %> left to enter.
      <% end %>
    
      <% if now >= contest.entrydeadline and now < contest.votingstart %>
        Entries are rendering.  Voting will start on <%=h contest.votingstart.getlocal.strftime("%A %B %d, %Y at %I:%M %p (%Z)") %>.
        <% if current_user and current_user.may_vote? %>
        Come back in <%= time_between(contest.entrydeadline, Contest.current_time) %> to vote.
        <% end %>
      <% end %>
      
      <% if now >= contest.votingstart and now < contest.votingend %>
        Voting has begun.  Votes must be submitted by <%=h contest.votingend.getlocal.strftime("%A %B %d, %Y at %I:%M %p (%Z)") %>.
        <%= time_between(contest.votingend, Contest.current_time) %> left to vote.
      <% end %>
    
      <% if now > contest.votingend %>
        Voting is now closed.  See the results of the contest <%= link_to "here", "results" %>.
      <% end %>
    
    <% else %>
      The contest is taking a vacation.
      <% nc = Contest.next_contest %>
      <% if nc %>
        Come back <% nc.startdate.getlocal.strftime("%A %B %d, %Y at %I:%M %p (%Z)") %> to enter in the next one.
      <% end %>
    <% end %>
    
    </div>
  </div>

</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round box">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>